Feature4
youngEmployeeProject/researchZenHubProject pull request #44
Opened 2018-12-02 06:56 UTC by Sempu-Mizuha

**Title**
White the Title.

**In progress**
- [ ] details 1
- [ ] details 2
- [ ] details 3

**Reference file**
If you need reference file, you can note the location of it.
`target/directory/file`

**Additional context**
Add any other context or file name about the progress here.

2018-12-02 07:05 UTC, Sempu-Mizuha commented on README.md
> +コミット2
```suggestion
コミット2
```
おおおお

2018-12-02 07:11 UTC, Sempu-Momomi requested changes
ブロックだぜ！？

2018-12-02 07:11 UTC, Sempu-Momomi commented on README.md
> +コミット2
```suggestion
commit2
```
英語の方がいいわあ。

2019-03-10 03:38 UTC, Sempu-Momomi approved these changes

2019-03-10 03:38 UTC, merged